# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Integration_tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [labeled, opened, synchronize, reopened]

jobs:
  build:     
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.9
        channel-priority: strict
    - name: IntegrationTest
      shell: bash -l {0}
      run: python -m unittest discover tests
    - name: IntegrationTest2
      shell: bash -l {0}
      run: | 
        python tests/dummy.py 
        echo ${{ github.event.action }}
    - name: PushEvent
      if: $GITHUB_EVENT_NAME == 'PushEvent'
      shell: bash -l {0}
      run: echo "PushEvent"
    - name: PR event with integration label
      if: ( github.event_name == 'PullRequest'  && contains(github.event.pull_request.labels.*.name, 'integration' ))
      shell: bash -l {0}
      run: echo "PR with integration label"
    - name: PR event
      if: github.event_name == 'pull_request'
      shell: bash -l {0}
      run: echo "PR event"
    - name: event with integration label
      if: contains(github.event.pull_request.labels.*.name, 'integration' )
      shell: bash -l {0}
      run: echo "has integration label"
    - name: Push event or PR with integration label
      if: |
        github.event_name == 'PushEvent' ||
        ( github.event_name == 'PullRequest'  && contains(github.event.pull_request.labels.*.name, 'integration' ))
      shell: bash -l {0}
      run: echo "Is push to master or PR to master with integration label - intended usage!"
