# Copied from https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#issue_comment
# This workflow _only_ works for the default branch!

on: issue_comment

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Comment on PR #${{ github.event.issue.number }} with:"
          echo "${{ github.event.comment.body }}"
      - name: DebugInfo
        uses: hmarr/debug-action@v2
      - name: Checkout
        if: ${{ github.event.comment.body == 'black' }}
        uses: actions/checkout@v2
      - name: Checkout Pull Request
        if: ${{ github.event.comment.body == 'black' }}
        run: hub pr checkout ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: test
        if: ${{ github.event.comment.body == 'black' }}
        uses: psf/black@stable
        with:
          options: ""
      - name: commit
        if: ${{ github.event.comment.body == 'black' }}
        run: |
          git config --local user.email "pyiron@mpie.de"
          git config --local user.name "pyiron-runner"
          git commit -m "Use black formatting" -a
      - name: DebugInfo2
        uses: hmarr/debug-action@v2
      #- name: UpdateDependabotPR push
      #  if: ${{ github.event.comment.body == 'black' }}
      #  uses: ad-m/github-push-action@master
      #  with:
      #   branch: ${{ github.event.issue.pull_request.head.ref }}
          

  issue_commented:
    # This job only runs for issue comments
    name: Issue comment
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Comment on issue #${{ github.event.issue.number }}"
