# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: comment trigger

on: issue_comment
  types: [created, edited]

jobs:
  name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Comment on PR #${{ github.event.issue.number }}"
  pr_build:
    if: ${{ github.event.issue.pull_request}}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.9
        channel-priority: strict
    - name: Test
      shell: bash -l {0}
      run: python -m unittest discover tests
    - name: Test2
      shell: bash -l {0}
      run: python tests/dummy.py
