# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.11
        channel-priority: strict
    - name: Test
      shell: bash -l {0}
      run: python -m unittest discover tests
    - name: Test2
      shell: bash -l {0}
      run: python tests/dummy.py
      
  job2:
    runs-on: ubuntu-latest
    steps:
    - name: fail
      shell: bash -l {}
      run: bash < exit 3

  job3:
    runs-on: ubuntu-latest
    needs: [build, job2]
    if: ${{ always() && build.conclusion == 'success'}}
    steps:
    - name: report
      shell: bash -l {0}
      run: bash < echo TaDa
  
